title: RoveSoSimulator
description: Autonomous Rover Testing Simulator in Unreal Engine 5
remote_theme: "godalming123/minimal"
plugins:
- jekyll-remote-theme
color-scheme: "auto-default-dark"
logo: "https://i.postimg.cc/XYtdp84Z/logo.png"
navigation: [
  {
    url: "RoveSoSimulator/",
    name: "Home"
  },
  {
    url: "RoveSoSimulator/setup",
    name: "Getting Started"
  },
  {
    url: "RoveSoSimulator/linux-setup",
    name: "Linux Setup Help"
  },
  {
    url: "RoveSoSimulator/documentation",
    name: "Documentation"
  }
]