title: RoveSoSimulator
description: Autonomous Rover Testing Simulator in Unreal Engine 5
remote_theme: "godalming123/minimal"
plugins:
  - jekyll-remote-theme
color-scheme: "auto-default-dark"
logo: "https://i.postimg.cc/XYtdp84Z/logo.png"
navigation:
  - link: "/pages/index.html"
    name: "Home"
  - link: "/pages/setup.html"
    name: "Getting Started"
  - link: "/pages/linux-setup.html"
    name: "Linux Setup Help"
  - link: "/pages/documentation.html"
    name: "Documentation"
  - link: "/pages/diversion.html"
    name: "Diversion"
  - link: "/pages/importing-rover.html"
    name: "Importing Rover"
  - link: "/pages/importing-talos-2.html"
    name: "Importing Talos - 2"
  - link: "/pages/lidar-point-cloud-generation-system.html"
    name: "Lidar Point Cloud Generation System"
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
