# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/ccowen/Documents/Linux_Unreal_Engine_5.5.1

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	RoveSoSimulator-Android-DebugGame  \
	RoveSoSimulator-Android-Development  \
	RoveSoSimulator-Android-Shipping  \
	RoveSoSimulator-Linux-DebugGame  \
	RoveSoSimulator-Linux-Development  \
	RoveSoSimulator-Linux-Shipping  \
	RoveSoSimulator-LinuxArm64-DebugGame  \
	RoveSoSimulator-LinuxArm64-Development  \
	RoveSoSimulator-LinuxArm64-Shipping  \
	RoveSoSimulator \
	RoveSoSimulatorEditor-Linux-DebugGame  \
	RoveSoSimulatorEditor-Linux-Development  \
	RoveSoSimulatorEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend RoveSoSimulatorEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug RoveSoSimulatorEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

RoveSoSimulator-Android-DebugGame:
	 $(BUILD) RoveSoSimulator Android DebugGame  -Project="/home/ccowen/Documents/MarsRoverDesignTeam/RoveSoSimulator/RoveSoSimulator.uproject" $(ARGS)

RoveSoSimulator-Android-Development:
	 $(BUILD) RoveSoSimulator Android Development  -Project="/home/ccowen/Documents/MarsRoverDesignTeam/RoveSoSimulator/RoveSoSimulator.uproject" $(ARGS)

RoveSoSimulator-Android-Shipping:
	 $(BUILD) RoveSoSimulator Android Shipping  -Project="/home/ccowen/Documents/MarsRoverDesignTeam/RoveSoSimulator/RoveSoSimulator.uproject" $(ARGS)

RoveSoSimulator-Linux-DebugGame:
	 $(BUILD) RoveSoSimulator Linux DebugGame  -Project="/home/ccowen/Documents/MarsRoverDesignTeam/RoveSoSimulator/RoveSoSimulator.uproject" $(ARGS)

RoveSoSimulator-Linux-Development:
	 $(BUILD) RoveSoSimulator Linux Development  -Project="/home/ccowen/Documents/MarsRoverDesignTeam/RoveSoSimulator/RoveSoSimulator.uproject" $(ARGS)

RoveSoSimulator-Linux-Shipping:
	 $(BUILD) RoveSoSimulator Linux Shipping  -Project="/home/ccowen/Documents/MarsRoverDesignTeam/RoveSoSimulator/RoveSoSimulator.uproject" $(ARGS)

RoveSoSimulator-LinuxArm64-DebugGame:
	 $(BUILD) RoveSoSimulator LinuxArm64 DebugGame  -Project="/home/ccowen/Documents/MarsRoverDesignTeam/RoveSoSimulator/RoveSoSimulator.uproject" $(ARGS)

RoveSoSimulator-LinuxArm64-Development:
	 $(BUILD) RoveSoSimulator LinuxArm64 Development  -Project="/home/ccowen/Documents/MarsRoverDesignTeam/RoveSoSimulator/RoveSoSimulator.uproject" $(ARGS)

RoveSoSimulator-LinuxArm64-Shipping:
	 $(BUILD) RoveSoSimulator LinuxArm64 Shipping  -Project="/home/ccowen/Documents/MarsRoverDesignTeam/RoveSoSimulator/RoveSoSimulator.uproject" $(ARGS)

RoveSoSimulator: RoveSoSimulator-Linux-Development

RoveSoSimulatorEditor-Linux-DebugGame:
	 $(BUILD) RoveSoSimulatorEditor Linux DebugGame  -Project="/home/ccowen/Documents/MarsRoverDesignTeam/RoveSoSimulator/RoveSoSimulator.uproject" $(ARGS)

RoveSoSimulatorEditor-Linux-Development:
	 $(BUILD) RoveSoSimulatorEditor Linux Development  -Project="/home/ccowen/Documents/MarsRoverDesignTeam/RoveSoSimulator/RoveSoSimulator.uproject" $(ARGS)

RoveSoSimulatorEditor: RoveSoSimulatorEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/ccowen/Documents/MarsRoverDesignTeam/RoveSoSimulator/RoveSoSimulator.uproject" -Game 

.PHONY: $(TARGETS)
