blank_issues_enabled: true
contact_links:
  - name: Report a Security Vulnerability
    url: mailto:marsrover@mst.edu?subject=%5BGitHub%20Security%5D%20Vulnerability%20Reporting
    about: Found a security vulnerability? Report it directly to the Mars Rover Design Team via email. Please do not disclose publicly.
